export const setBackgroundType = (bgType) => ({ type: "SET_BACKGROUND_TYPE", bgType })
export const setBackgroundColor = (color) => ({ type: "SET_BACKGROUND_COLOR", color })
export const setBackgroundImage = (url) => ({ type: "SET_BACKGROUND_IMAGE", url })
export const setDesktopSize = (width, height) => ({ type: "SET_DESKTOP_SIZE", width, height })
export const setIsSettingsMenuOpen = (value) => ({ type: "SET_IS_SETTINGS_MENU_OPEN", value })